version: '3.1'
services:
  app:
    container_name: springboot-courseword
    image: springboot-postgresql
    build: ./
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgresqldb:5432/coursework
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=felikstitov
      - POSTGRES_DB=coursework

  proxy:
    image: nginx:1.11 # this will use the latest version of 1.11.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src/main/resources/templates/static:/data/static/
    depends_on:
      - app