upload:
  path: "static"
server:
  port: 8080
  error:
    path: /error
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://ec2-54-155-35-88.eu-west-1.compute.amazonaws.com:5432/d5l6qd6ecd4mt7
    username: tmoihkvpzmopej
    password: 69eb9120ef5da0f80c1c72bb7c8c0ac4aa9f2dd65e02f0ae977ee28fad38a6ec
  jpa:
    database: postgresql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 1024MB
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: servermail781227@gmail.com
    password: Admin1905!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

