upload:
  path: "static"
server:
  error:
    path: /error
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/coursework}
    username: ${JDBC_DATABASE_USERNAME:felikstitov}
    password: ${JDBC_DATABASE_PASSWORD:12345678}
  jpa:
    database: postgresql
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 1024MB
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: servermail781227@gmail.com
    password: Admin1905!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

