upload:
  path: "static"
server:
  port: 8081
  error:
    path: /error
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coursework
    username: felikstitov
    password: 12345678
  jpa:
    database: postgresql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 1024MB
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: servermail781227@gmail.com
    password: Admin1905!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

